### ISSUE TITLE
Please Update for Latest Anki version with Qt6 + Keyboard input bug

### ISSUE THREAD

**Issue by mahfuj2507** [trgkanki/ankitime#31]
# Bug report:

![image](https://github.com/trgkanki/ankitime/assets/117604264/d51c4886-b376-470b-9df9-d05136423320)

## Describe the bug:
Shows the above picture

## Reproduction step:
On clicking "study" in deck, the picture above pops up. This started after update to this latest version of Anki (the update to Qt6 and FSRS)

## Expected behavior:
No popup.

## Anki/OS versions
Anki version 23.12.1 Qt6 -Windows 10

## Additional context:

Debug Info-
Anki 23.12 (55ef11af)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.19045

Traceback (most recent call last):
  File "aqt.webview", line 50, in cmd
  File "aqt.webview", line 157, in _onCmd
  File "aqt.webview", line 686, in _onBridgeCmd
  File "aqt.overview", line 97, in _linkHandler
  File "aqt.main", line 740, in moveToState
  File "aqt.main", line 761, in _reviewState
  File "aqt.reviewer", line 174, in show
  File "aqt.reviewer", line 194, in refresh_if_needed
  File "aqt.reviewer", line 250, in nextCard
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 81, in repl
  File "C:\Users\Mahfuz\AppData\Roaming\Anki2\addons21\998250600\__init__.py", line 53, in afterInitWeb
    QWebEngineSettings.PlaybackRequiresUserGesture, False
AttributeError: type object 'QWebEngineSettings' has no attribute 'PlaybackRequiresUserGesture'

**Comment by mahfuj2507** [comment]
I tried to reinstall 
and now i get pop up on anki startup
Debug info-
Anki 23.12 (55ef11af)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.19045

When loading Anki Time anti-distraction helper:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\Mahfuz\AppData\Roaming\Anki2\addons21\998250600\__init__.py", line 34, in <module>
    from .utils import openChangelog
  File "C:\Users\Mahfuz\AppData\Roaming\Anki2\addons21\998250600\utils\openChangelog.py", line 44, in <module>
    showChangelogOnUpdate()
  File "C:\Users\Mahfuz\AppData\Roaming\Anki2\addons21\998250600\utils\openChangelog.py", line 40, in showChangelogOnUpdate
    dlg = MiniBrowser(None, "CHANGELOG.html")
  File "C:\Users\Mahfuz\AppData\Roaming\Anki2\addons21\998250600\utils\MiniBrowser.py", line 56, in __init__
    self.setWindowFlags(Qt.Window)
AttributeError: type object 'Qt' has no attribute 'Window'

**Comment by mahfuj2507** [comment]
If anyone drops here to find sol. to this bug, i basically fixed it using chatgpt.
Fix- i had to just to go in addon folder>__ init __.py> edit> disable these three lines of code by adding a "#" infront of it. This is how it looks after adding #.
```
#    self.web.settings().setAttribute(
#        QWebEngineSettings.PlaybackRequiresUserGesture, False
#    )
```

also there was an issue with the addon not registering keyboard input so i also edited the js file (main.min.js), searched in notepad for "key" until i got to this area of line: 
```
const a=["load","mousemove","mousedown","click","keydown","keypress","keyup","touchstart","touchmove"]
```

{ "keypress","keyup", } was added to the line by me additionally as you can see above. it was not there before. this way it fixed the keyboard input register problem.

**Comment by mahfuj2507** [comment]
Homemade hotfix by a computer noob with 0 coding knowledge so please dont ask me any questions.
(P.S: also this first bug doesn't happen in Qt5 versions of Anki)

**Comment by wudidepan** [comment]
Perfectly solved the Qt6 adaptation and keyboard bug, thank you very much

**Comment by phu54321** [comment]
Thanks for the fix! Gonna integrate that
